In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("parkinson.csv")

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
name                195 non-null object
MDVP:Fo(Hz)         195 non-null float64
MDVP:Fhi(Hz)        195 non-null float64
MDVP:Flo(Hz)        195 non-null float64
MDVP:Jitter(%)      195 non-null float64
MDVP:Jitter(Abs)    195 non-null float64
MDVP:RAP            195 non-null float64
MDVP:PPQ            195 non-null float64
Jitter:DDP          195 non-null float64
MDVP:Shimmer        195 non-null float64
MDVP:Shimmer(dB)    195 non-null float64
Shimmer:APQ3        195 non-null float64
Shimmer:APQ5        195 non-null float64
MDVP:APQ            195 non-null float64
Shimmer:DDA         195 non-null float64
NHR                 195 non-null float64
HNR                 195 non-null float64
status              195 non-null int64
RPDE                195 non-null float64
DFA                 195 non-null float64
spread1             195 non-null float64
spread2             195 non-null floa

In [23]:
park=data.drop(["name"],axis=1)
#park=data[data["status"]==1]

In [33]:
park.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 23 columns):
MDVP:Fo(Hz)         195 non-null float64
MDVP:Fhi(Hz)        195 non-null float64
MDVP:Flo(Hz)        195 non-null float64
MDVP:Jitter(%)      195 non-null float64
MDVP:Jitter(Abs)    195 non-null float64
MDVP:RAP            195 non-null float64
MDVP:PPQ            195 non-null float64
Jitter:DDP          195 non-null float64
MDVP:Shimmer        195 non-null float64
MDVP:Shimmer(dB)    195 non-null float64
Shimmer:APQ3        195 non-null float64
Shimmer:APQ5        195 non-null float64
MDVP:APQ            195 non-null float64
Shimmer:DDA         195 non-null float64
NHR                 195 non-null float64
HNR                 195 non-null float64
status              195 non-null int64
RPDE                195 non-null float64
DFA                 195 non-null float64
spread1             195 non-null float64
spread2             195 non-null float64
D2                  195 non-null flo

In [50]:
data["status"].value_counts()

1    147
0     48
Name: status, dtype: int64

In [51]:
park1=park["status"]

In [79]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(park,random_state=20,test_size=0.2)

In [83]:
print(train.shape, test.shape)

(156, 23) (39, 23)


In [80]:
from sklearn.linear_model import LogisticRegression

In [101]:
clf = LogisticRegression()
X = train.drop(["status"], axis=1)
y = train["status"]
clf.fit(X, y)
X_test=test.drop(["status"],axis=1)
pred=clf.predict(X_test)
pred

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [103]:
from sklearn.metrics import accuracy_score

In [106]:
accuracy_score(pred,test["status"])

0.79487179487179482

In [109]:
y.shape

(156,)

In [124]:
y.reshape(1,-1).shape

C:\Users\Diva\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


(1, 156)

In [127]:
from sklearn.metrics import confusion_matrix

In [134]:
confusion_matrix(test["status"],pred)

array([[ 7,  5],
       [ 3, 24]], dtype=int64)

In [135]:
from sklearn.ensemble import RandomForestClassifier

In [156]:
rndfst = RandomForestClassifier(random_state=20)
X = train.drop(["status"], axis=1)
y = train["status"]
rndfst.fit(X, y)
X_test=test.drop(["status"],axis=1)
pred=rndfst.predict(X_test)
pred

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [157]:
accuracy_score(pred,test["status"])

0.82051282051282048

In [141]:
confusion_matrix(test["status"],pred)

array([[11,  1],
       [ 5, 22]], dtype=int64)

In [142]:
from sklearn.externals import joblib

In [149]:
joblib.dump(rndfst, "forest_model.pkl")
forest_model_reload = joblib.load("forest_model.pkl")
forest_model_reload

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)